services:
  - type: web
    name: holbos-attendance-erp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn holbos_attendance.holbos_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: holbos_attendance.holbos_project.settings
      - key: SECRET_KEY
        generate: true
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        value: "${{DATABASE_URL}}"
      - key: ALLOWED_HOSTS
        value: "*"
    staticPublishPath: staticfiles
    healthCheckPath: "/"

databases:
  - name: holbos-db
    postgres:
      version: 15
