# Generated by Django 6.0.3 on 2026-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
