# Generated by Django 6.0.3 on 2026-05-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_is_parent_to_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
