# Generated by Django 6.0.3 on 2026-05-16 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_trainer_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(max_length=20)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_bookings', to='attendance.student')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
