# Generated by Django 6.0.3 on 2026-05-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_compensationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='has_claimed_account',
            field=models.BooleanField(default=False),
        ),
    ]
