# Generated by Django 6.0.3 on 2026-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_trainer_has_claimed_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
