# Generated by Django 6.0.3 on 2026-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_trainer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
